---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: bridge
  namespace: keptn
spec:
  hosts:
  - "bridge.keptn.XX.XX.XXX.XX.xip.io"
  gateways:
  - keptn-gateway
  http:
    - route:
      - destination:
          host: bridge.keptn.svc.cluster.local
      websocketUpgrade: true
